### ISSUE TITLE
[Sugerencia de tema] Three.js library 

### ISSUE THREAD

**Issue by thamaragerigr** [OSWeekends/request-for-talks#11]
@stivaliserna haces cosas muy chulas con three.js:

https://codepen.io/stivaliserna/pen/ExKMLjP
https://codepen.io/stivaliserna/pen/xxVKYjM

Si la pudieran convencer de hacer una charla o lo que sea de como lo hace 🙏😭

**Comment by baumannzone** [comment]
Ya he contactado con ella, a ver qué dice 👀

**Comment by thamaragerigr** [comment]
yasss 🔥🔥

**Comment by stivaliserna** [comment]
¡Hola! ^^

Muchas gracias por el mention ❤️ 

> Ya he contactado con ella, a ver qué dice 👀

Creo que no he recibido nada, ¿me escribiste por mail? 😄 

Con gusto lo hablamos, a mí me encantaría, pero debo ver primero los requisitos porque no sé si tengo el nivel necesario haha.

**Comment by baumannzone** [comment]
Te mandé invitación por LinkedIn :DD
¿Qué requisitos? Aquí no hacemos examen de acceso 😋 jaja

**Comment by baumannzone** [comment]
Contamos contigo para el 19 de diciembre, es ok @stivaliserna ?

**Comment by stivaliserna** [comment]
Yess! 😃

**Comment by baumannzone** [comment]
¿@thamaragerigr esto lo podemos cerrar ya?

**Comment by thamaragerigr** [comment]
Sipi! Stivali lo ha petado! ^_^
