### ISSUE TITLE
[Charla] DDD o como aprender a hablar balleno

### ISSUE THREAD

**Issue by ogomezso** [OSWeekends/request-for-talks#13]
Soy Oscar Gómez soy un Software Craftsman ahora mismo para ING Spain, me dedico al Backend y Devops y si... sobre todo en mundo JVM...

Alguna vez has tenido que empezar un proyecto/producto... has tenido esa sensación de ser un marciano y que todo te suena a maricano... es mas tu eres el marciano???.... DDD es un conjunto de practicas que nos ayuda a hablar balleno!

**Comment by baumannzone** [comment]
Hola Óscar, usas twitter?

**Comment by ogomezso** [comment]
Sip @oskarflesh

**Comment by ogomezso** [comment]
Buenas a peticion de @baumannzone  os explico un poco mas de lo que va esto...
Basicamente se trata una imtroduccion de Domain Driven Design, un conjunto de practicas que nos ayudan a desarrollar software o mas bien productos basados en el conocimiento de dominio, es decir consiguiendo que negocio e IT hablemos el mismo idioma. 
A todo esto soy @oskarflesh en twitter llevo algun tiempo formando parte de la comunidad OSW ;)

**Comment by baumannzone** [comment]
Enero te encaja?

**Comment by ogomezso** [comment]
casi mejor febrero... que en enero tengo muchas cosas ya!

pero si veis que no encaja bien me puedo apañar para darla en enero... que fecha seria?

**Comment by thamaragerigr** [comment]
¡Hola! Febrero esta perfect! ^_^ Todavía no tenemos fecha concreta para el evento de febrero pero te avisamos en cuanto sepamos!

**Comment by baumannzone** [comment]
Hola Oscar. Confirmamos para Marzo. ✅

**Comment by ogomezso** [comment]
Perfecto 13 o 20 habíamos quedado no?
