### ISSUE TITLE
[Charla] Introducción a Verdaccio

### ISSUE THREAD

**Issue by juanpicado** [OSWeekends/request-for-talks#18]
Hello !

### Charla propuesta

Hoy en dia todos los web developer usan JavaScript, de una u otra manera se requieren instalar paquetes publicar con un manejador de paquetes eg: `npm` y eventualmente se necesita publicar los propios. Esta charla es sobre **Verdaccio**, un pequeño servidor en Node.js que te permite publicar paquetes privados, sirve como proxy para instalar paquetes desde npmjs o cualquier otro registro y con interfaz de usuario incluido. Se puede instalar desde npmjs y docker. 

Incluye noticias sobre el futuro Verdaccio 5

https://verdaccio.org/

### Sobre mi

Mi nombre es Juan, soy Senior Front-End en eBay y mi tiempo libre hago open source manteniendo el proyecto Verdaccio.

GitHub: https://github.com/juanpicado
Twitter: https://twitter.com/jotadeveloper

### Charlas anteriores

https://www.youtube.com/playlist?list=PLmAPAx5GNNtxkZiYcM7NpjpzST4qzQQwh

**Comment by thamaragerigr** [comment]
¡Hola! ¡Nos superencanta la idea! ʕ•ᴥ•ʔ ¿Te vendría bien para mayo? ^_^

**Comment by juanpicado** [comment]
> ¡Hola! ¡Nos superencanta la idea! ʕ•ᴥ•ʔ ¿Te vendría bien para mayo? ^_^

Si, no hay problema :+1: solo necesito saber 2 semanas anticipado, asi que Mayo mas que suficiente :upside_down_face:
