### ISSUE TITLE
[Charla] Testeando Accesibilidad Web 

### ISSUE THREAD

**Issue by bolonio** [OSWeekends/request-for-talks#19]
## Sobre mi

Hola, me llamo Adrián Bolonio. Soy el engineering manager de un equipo de ingenieros, desarrollador frontend, y gran defensor de la Accesibilidad Web (a11y). Soy de Madrid, pero desde 2012 vivo y trabajo en Viena (Austria). Cuando no estoy en la oficina me gusta disfrutar de una buena lectura, dedicarle tiempo a cocinar alguna deliciosa receta, o practicar my afición por visitar nuevos lugares por el mundo.

## La Charla

Queremos que nuestro sitio web sea eficaz, eficiente y satisfactorio para el usuario, pero muchas veces no pensamos en la experiencia del usuario para las personas con discapacidades, incluidas las personas con discapacidades relacionadas con la edad. ¿Cómo pueden ayudarnos las pruebas automáticas y las pruebas manuales a mejorar nuestra interfaz?

Cuando desarrollamos un nuevo sitio web, a menudo ponemos mucho trabajo en el diseño, para que sea bonita y utilizable. En otras palabras, queremos que nuestra web sea efectiva, eficiente y satisfactoria para el usuario. Pero muchas veces no pensamos en la experiencia del usuario para las personas con discapacidades, incluidas las personas con discapacidades relacionadas con la edad.

Accesibilidad web (a11y) significa que las personas con discapacidad pueden percibir, comprender, navegar e interactuar con sitios web y herramientas, y que pueden contribuir igualmente sin barreras ”. (Fuente: W3C - Web Accessibility Initiative). Nuestro papel como desarrolladores frontend es crear interfaces claras para que las personas entiendan y se preocupen por los datos, independientemente de sus discapacidades o impedimentos, pero lo que nosotros, los desarrolladores, a menudo olvidamos es asegurarnos de que el código que escribimos siga las "Web Content Accessibility Guidelines" (WCAG), y la única forma de lograrlo es mediante test, ya sea manuales o automatizados.

Los tests automatizados de accesibilidad web pueden liberar a nuestro equipo de QA de los tests manuales de cada parte de nuestra aplicación, pero, no pueden hacer que nuestro sitio sea accesible de forma automática y mágica.

Deberíamos usar tests automatizados de accesibilidad web como un paso de un proceso de tests más grande. No olvidemos que solo se puede detectar automáticamente del 20% al 50% de todos los problemas de accesibilidad.

Enseñaré algunas herramientas de tests, bibliotecas y técnicas para aumentar la cobertura de tests de tu código con un simple ejemplo con una aplicación React.

## Fechas

No tengo mucho problema de fechas, pero todo es hablar de cuando os vendría bien a vosotros :)

## Contacto

Web: http://adrianbolonio.com/
Twitter: https://twitter.com/bolonio
GitHub: https://github.com/bolonio
Linkedin: https://www.linkedin.com/in/adrianbolonio/

Podeis encontrar todas las charlas que he dado aquí (con videos) https://www.adrianbolonio.com/talks

**Comment by baumannzone** [comment]
Brutal. 🌶️ 🔥

**Comment by thamaragerigr** [comment]
¡Nos superencanta! Estabamos pensando en hacer un OSW con temática de accesibilidad en Mayo por el **_Global Accessibility Awareness Day_**  ¿Qué opinas de la idea?

**Comment by bolonio** [comment]
El **_Global Accessibility Awareness Day_** este año será el 20 de Mayo. Como ya dije, no tengo muchos problema de fechas, todo es hablarlo y encontrar un día que nos cuadre a todos, pero si haceis un especial con esa temática estaría genial, contad conmigo :)

**Comment by AlenaNik** [comment]
Había propuesto a Thamara invitar a dos chicas para **_Global Accessibility Awareness Day_** 

- Nuria Azanza [Su charla en TotoConf](https://totoconf.tech/nuria-aranza/ )fue espectacular la experiencia que contó siendo una persona ciega
- Anna E. Cook (en inglés) [Twitter](https://twitter.com/annaecook)
- Las chicas que escribieron el[ libro ](https://twitter.com/Edutech_Project/status/1326534385349193728) "Accesibilidad Web". Son [Olga Revilla Muñoz](https://twitter.com/Itakora) y [Olga Carreras Montoto](https://twitter.com/olgacarreras)

**Comment by AlenaNik** [comment]
Había propuesto a Thamara invitar a alguna de las tres chicas para **_Global Accessibility Awareness Day_** 
A ver que os parece ✨

Nuria Azanza Su charla en [TotoConf](https://totoconf.tech/nuria-aranza/) fue espectacular la experiencia que contó siendo una persona ciega
[Anna E. Cook](https://twitter.com/annaecook) (en inglés) Twitter
Las chicas que escribieron el[ libro "Accesibilidad Web"](https://twitter.com/Edutech_Project/status/1326534385349193728). Son [Olga Revilla Muñoz](https://twitter.com/Itakora) y [Olga Carreras Montoto](https://twitter.com/olgacarreras)

**Comment by thamaragerigr** [comment]
¡Muchas gracias Alena! ʕ•́ᴥ•̀ʔっ♡ ¡Veremos a quienes logramos convencer! 😈

**Comment by bolonio** [comment]
Hola hola, cómo van los preparativos de la edición de accesibilidad? Sigue en pie? Puedo ayudaros en algo?

PS: Invitad a Alena al evento!!!

**Comment by thamaragerigr** [comment]
¡Hola!  Sip, sigue en pie. Ahora estamos preparando el de abril pero cuando empecemos con los preparativos para el de mayo te avisamos! (intentamos convencer a Alena de venir pero no puede, a ver si tu la convences 😈)

**Comment by AlenaNik** [comment]
Estoy invitada, pero mi vida es muy loca para dar una charla 😝 

Necesitaís ayuda con organización y difusión? 
Sobre todo si quereís que os ayudemos con mini presentación del principio o intro, contad con nosotros, `hacemos una call`! 🙋🏼‍♀️

**Comment by thamaragerigr** [comment]
¿¡Te apetece hacer una micro intro/presentación!? ¡Si porfavorrrr! 🥺👉👈
