### ISSUE TITLE
[micro charla] - Iniciativa #Hourofcode promovida por la ONG Code.org

### ISSUE THREAD

**Issue by javimostoles** [OSWeekends/request-for-talks#2]
Hola

Mi nombre es Javier Pérez y trabajo como desarrollador Front End en Accenture (Liquid Squad). 

Se trata de una iniciativa global educativa llamada Hour of Code, promovida por la organización **Code.org**, que tiene lugar en más 180 países y que se celebra en diciembre coincidiendo con la semana de las Ciencias de la Computación **_(9 al 15 de diciembre)_**. 

Esta iniciativa, pretende acercar la programación y el desarrollo del pensamiento computacional a estudiantes de todo el mundo y de todas las edades, beneficiando sólo el año pasado a 100 millones de estudiantes. 

En la charla expondré mi experiencia personal al colaborar como voluntario en el colegio de mi hijo. No se trata de una charla técnica pero en ella se mostrarán ejemplos de algunos de las actividades que realizamos. 

https://slides.com/javierperezdepedro/hour-of-code-2018/

Muchas gracias.

Podéis contactarme aquí:

Twitter: @javimostoles
Skype: javi.perez.depedro
LinkedIn: https://www.linkedin.com/in/javimostoles/

**Comment by baumannzone** [comment]
¿Cuándo te gustaría dar la charla?

Sabes que puedes dar la charla con tu hijo,¿verdad?

**Comment by baumannzone** [comment]
Apuntamos : 30 minutos, Sábado 14 diciembre

**Comment by javimostoles** [comment]
Modificación texto Agenda 14 diciembre --> @baumannzone 

Hablaremos de **Hour of Code**, una iniciativa educativa global promovida por la organización code.org, que tiene lugar en más 180 países y coincide con la semana de las Ciencias de la Computación (9 al 15 de diciembre).

En la charla os hablaré de mi experiencia personal como voluntario en el colegio de mi hijo. No se trata de una charla técnica pero veremos algunos de los proyectos que hemos desarrollado con los alumnos.

En la charla hablaremos de:

👨‍💻 #HourOfCode
👽 #SemanaMarciana y sus pollitos 🐥🐥🐥
🐞 #Escornabot
🤖 #OttoDIY
🚗 #OpenLedRace
🌈 #CircuitPlayground
