### ISSUE TITLE
Mesa redonda: CI para ofertas de trabajo

### ISSUE THREAD

**Issue by RafaelAybar** [OSWeekends/request-for-talks#4]
Hola, tengo un proyecto que intenta medir la calidad de las ofertas laborales. 

Para ello, a través de Apis de Portales de empleo se calcularía la rotación histórica de la compañia, y además se podrían hacer test unitarios que impidan que se cuelen ofertas basura. 

Me gustaría hacer una  mesa redonda donde poder desarrollar esta idea y salir con una conclusión clara de cómo luchar contra el spam de ofertas de empleo basura. 

La fecha en principio es cuando os venga bien
Este es el repositorio de GitHub:
https://github.com/RafaelAybar/qa-empleo

Cc: @baumannzone

**Comment by RafaelAybar** [comment]
@UlisesGascon Buenas, ¿se sabe algo de la propuesta?

**Comment by RafaelAybar** [comment]
@baumannzone ¿Podría haber hueco para Febrero?

**Comment by baumannzone** [comment]
Lo estamos revisando, te avisamos cuando sepamos algo.
