### ISSUE TITLE
[charla] Frontend & Microservicios

### ISSUE THREAD

**Issue by kevinccbsg** [OSWeekends/request-for-talks#6]
# Title / Título

Frontend & Microservicios

# Description / Descripción

Trabajar en una arquitectura de microservicios es un reto que podemos encontrar en muchas de nuestras empresas. Aunque cada microservicio en sí es independiente y podemos trabajar con el de manera aislada, a veces, nos encontramos con que el desarrollo del Frontend no siempre está tan aislado, por lo que tenemos que crear entornos de desarrollo complejos para trabajar de manera local. Esto en muchos casos puede suponer un proceso complicado para los desarrolladores frontend o para el onBoarding de nuevos compañeros.

En esta charla, os compartiré mi experiencia de como desarrollamos una de nuestras aplicaciones en una arquitectura de microservicios, resolviendo estos problemas y consiguiendo que la parte frontend pueda centrarse en lo que mejor sabe hacer, crear experiencias de usuario increíbles.

# Speaker Bio / Bio del Ponente

Javascript Developer en Guidesmiths, apasionado de las tecnologías Web y la formación constante. Actualmente me dedico con tecnologías como Node.js, React, Docker, MongoDB y Cypress creando Microservicios y aplicaciones para empresas de Holanda y Suecia. También imparto formación de Javascript para distintas empresas.

# Level / Nivel

Intermedio

# Duration / Duración

45 minutos

# Constraints / Condicionantes

Algunas semanas lunes, martes y jueves no puedo pero dependería de la fecha. Por todo lo demás sin problemas.

**Comment by baumannzone** [comment]
Los eventos los hacemos los sábados, en campus Madrid.

Estás son las fechas: https://press-osw.netlify.com/posts/post-1/

**Comment by kevinccbsg** [comment]
Hola @baumannzone 

El sábado 22 de Febrero a mi me viene bien 👍 si tenéis hueco conmigo podéis contar.

**Comment by baumannzone** [comment]
Lo vamos viendo.

**Comment by baumannzone** [comment]
Hola, ¿como lo ves para Marzo, dia 21?

**Comment by kevinccbsg** [comment]
Me viene bien  😃

**Comment by baumannzone** [comment]
Apuntado: https://www.meetup.com/es-ES/Open-Source-Weekends/events/268795776/

**Comment by baumannzone** [comment]
Lo vamos planificando para enero 2021, te parece ok @kevinccbsg ?
