### ISSUE TITLE
[charla] The rise of the Web

### ISSUE THREAD

**Issue by loicortola** [OSWeekends/request-for-talks#7]
Hi, I'm Loïc and I just arrived in Madrid.  
I like trying to zoom-out on tech and understand everything about each technology I use. And I like to share this big picture with those who don't. This talk has been given to many conferences in France (Devoxx, Google DevFest, Paris.js, Node.js Paris, Lyon.js, etc...) and I would be happy to present it in english in Madrid :)

Description:  
Did you know where the name Mozilla came from?
Why JS is called Javascript in the first place?
How PHP, Java & .NET arrived?
20 years ago, no one sober would have used Javascript for anything else than stars coming out of your cursor. No way. In the early 2000’s, we would rather go for app-servers and the dynamic web.
Today, Flash and Java Applets are gone, JS rose from the ashes of the Browser and the Web won…
How did we get here?

That, detective, is the right question.

If you haven’t lived it, come discover the early steps of the web, the history of Netscape, the browser-war, and the rise of JS and the modern web.

Contact:  
[@loicortola](https://twitter.com/loicortola) on Twitter

Thanks a lot

**Comment by baumannzone** [comment]
Hi! Nice request. Let's try to make it for march. 

Our meetup calendar: https://press-osw.netlify.com/posts/post-1/

**Comment by loicortola** [comment]
Sounds great! I'm available that day :)

**Comment by baumannzone** [comment]
👌  
You will appear soon https://www.meetup.com/es-ES/Open-Source-Weekends/events/268795776/
